DEV-15556 added ScheduleWorkTimeResolver
dotsplatform/utils pull request #2
Opened 2023-05-17 06:33 UTC by olexandrpolosmak

2023-05-17 12:23 UTC, olexandrpolosmak commented on src/Dots/WorkTimeSchedule/WorkTimeSchedule.php
> +
lets:
 - remove bool, I suggest to use null
 - what about isAlwaysOn() ? Just I need to use him in many places
 - there is a bug, current logic expects that the schedule has whole seven days

2023-05-17 12:46 UTC, yehorherasymchuk requested changes

2023-05-17 12:46 UTC, yehorherasymchuk commented on src/Dots/WorkTimeSchedule/WorkTimeSchedule.php
> +    protected bool $alwaysOn = false;
alwaysOn  => anytime = true/false

2023-05-17 12:46 UTC, yehorherasymchuk commented on src/Dots/WorkTimeSchedule/WorkTimeSchedule.php
> +    protected bool $alwaysOn = false;
timezone not nullable

2023-05-17 12:46 UTC, yehorherasymchuk commented on src/Dots/WorkTimeSchedule/WorkTimeSchedule.php
> +    public function getStartTimeToday(): int|bool
use nullable

2023-05-18 11:48 UTC, yehorherasymchuk approved these changes

2023-05-18 11:48 UTC, merged